# _config.yml

title: Cheril Yogi
description: Mixing curiosity with real-world know-how, I make data engineering and science as approachable as your favorite story.
#author: Cheril Yogi
layouts_dir: _layouts

# URL-related settings
baseurl: "/cy2404.github.io" 

# Jekyll build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Navigation links
header_pages:
  - index.md
  - _pages/about.md
  - _pages/projects.md
  - _pages/blogs.md

# Permalinks
permalink: /:title/

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Additional settings
logo: ./images/headshot.png
# show_downloads: true # Uncomment this line if needed


